services:
  prd_db:
    container_name: "workoutDB"
    image: "postgres:16-alpine"
    volumes:
      - "./database/postgres-prd/data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped

  stg_db:
    container_name: "workoutDB_test"
    image: "postgres:16-alpine"
    volumes:
      - "./database/postgres-stg/data:/var/lib/postgresql/data:rw"
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
